sudo: true
language: java
addons:
  apt:
    packages:
      - oracle-java8-set-default
before_install:
  - curl -O https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/5.0.0-alpha5/elasticsearch-5.0.0-alpha5.deb && sudo dpkg -i --force-confnew elasticsearch-5.0.0-alpha5.deb && sudo service elasticsearch start
before_script:
  - sleep 15
  - curl -v http://localhost:9200/
after_success:
  - mvn -DrepoToken=$COVERALLS_REPO_TOKEN cobertura:cobertura coveralls:report